### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by davihaniel** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t8-blogviagem#7]
## Diagrama de Casos de Uso

O diagrama de casos de uso é o próximo passo após a elicitação de requisitos, que utiliza um modelo gráfico e uma tabela com as descrições sucintas dos casos de uso e dos atores. Ele contempla a fronteira do sistema e o detalhamento dos requisitos funcionais com a indicação dos atores, casos de uso e seus relacionamentos. 

As referências abaixo irão auxiliá-lo na geração do artefato “Diagrama de Casos de Uso”.

> **Links Úteis**:
> - [Criando Casos de Uso](https://www.ibm.com/docs/pt-br/elm/6.0?topic=requirements-creating-use-cases)
> - [Como Criar Diagrama de Caso de Uso: Tutorial Passo a Passo](https://gitmind.com/pt/fazer-diagrama-de-caso-uso.html/)
> - [Lucidchart](https://www.lucidchart.com/)
> - [Astah](https://astah.net/)
> - [Diagrams](https://app.diagrams.net/)

**Comment by davihaniel** [comment]
Task reaberta devido a mudanças que devem ser feitas

**Comment by SabrinaSFreitas** [comment]
https://lucid.app/lucidchart/2b164b42-ecd1-4862-bca0-3e999f4d1f42/edit?view_items=3QAsx061-wdg&invitationId=inv_126523b4-ca1d-417f-a14b-5bc85e02e9a4
